baseURL = "https://gunn3r1995.github.io/"
languageCode = "en-us"
title = "Shane's Blog"
theme = "hugo-theme-cleanwhite"

# Enable comments by entering your Disqus shortname
# disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
header_image = "img/home-bg-jeep.jpg"
SEOTitle = "Shane's Blog"
description = ""
keyword = "Keyword1, Keyword2"
slogan = "Hello World!"
image_404 = "img/404-bg.jpg"
title_404 = "404 Not Found :("

# Sidebar settings
sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
#sidebar_avatar = "img/avatar-Shane.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar_avatar = "img/Shane.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

featured_tags = true 
featured_condition_size = 1 

friends = false
bookmarks = true
about_me = true

[params.social]
rss            = true 
email          = "shane.smith@outlook.com"
#facebook      = "full profile url in facebook"
#twitter       = "full profile url in twitter"
linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
#instagram     = "full profile url in instagram"
github         = "https://github.com/gunn3r1995"
#  medium         = "full profile url in medium"
#pinterest     = "full profile url in pinterest"

[[params.bookmark_link]]
title =  "Google"
href =  "http://google.co.uk"

[[params.addtional_menus]]
title =  "BOOKS"
href =  "/top/books/"
[[params.addtional_menus]]
title =  "Useful"
href =  "/top/useful/"
[[params.addtional_menus]]
title =  "ABOUT"
href =  "/top/about/"
